name: CI

on:
  push:
    branches:
      - master
      - 'v*' # older version branches
    tags:
      - '*'

  pull_request: {}
  schedule:
  - cron:  '0 6 * * 0' # weekly, on sundays

jobs:
  test:
    name: "Node ${{ matrix.node }} - ${{ matrix.os }}"
    runs-on: "${{matrix.os}}-latest"

    strategy:
      matrix:
        os: ['ubuntu', 'windows', 'macOS']
        node: ['14', '16', '18']

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: install dependencies
      run: npm ci
    - name: test
      run: npm test

  floating-test:
    name: Floating dependencies
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: install dependencies
      run: npm install --ignore-shrinkwrap
    - name: test
      run: npm test

